import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  // static const Color primary = Color(0xFF52C1F7);
  // static const Color primary = Color(0xFFE73045);
  // static const Color primary = Color(0xFF7D1E6A);
  static const Color primary = Color(0xFF6746B9);
  // static const Color primary = Color(0xFF16C2B0);
  // static const Color primary = Color(0xFF317D73);
  // static const Color primary = Color(0xFF40A796);
  // static const Color primary = Color(0xFF7D1E6A);
  // static const Color primary = Color(0xFF008A9F);
  static const Color secondary = Color(0xFF6DC8F3);
  static const Color white = Color(0xFFFFFFFF);
  static const Color brokenWhite = Color(0xFFFAFAFA);
  static const Color black = Color(0xFF000000);
  static const Color green = Color(0xFF28CC9E);
  static const Color lightGrey = Color(0xFFDFDFDF);
  static const Color lightGrey2 = Color(0xFFEFEFEF);
  static const Color lightGrey3 = Color(0xFFF3F6F9);
  static const Color lightGrey4 = Color(0xFFF3F3F3);
  static const Color lightGrey5 = Color(0xFFE5E5E5);
  static const Color lightGrey6 = Color(0xFFF1F1F1);
  static const Color lightGrey7 = Color(0xFFA4A4A4);
  static const Color grey = Color(0xFF848484);
  static const Color grey2 = Color(0xFFB7B7B7);
  static const Color grey3 = Color(0xFF999999);
  static const Color darkGrey = Color(0xFF3A3A3A);
  static const Color darkGrey2 = Color(0xFF333333);
  static const Color red = Color(0xFFD32710);
  static const Color red2 = Color(0xFFEC0000);
  static const Color pink = Color(0xFFFF5784);
  static const Color charcoal = Color(0xFF1E1E1E);
  static const Color borderColor = Color(0xFFE8E8E8);
  static const Color paragraphColor = Color(0xFF555555);
  static const Color dividerColor = Color(0xFFE0E0E0);
  static const Color shadowColor = Color(0xFF3A3A3A);
  static const Color navy = Color(0xFF172441);
  static const Color blue = Color(0xFF376AED);
  static const Color softBlue = Color(0xFF9ADCFF);
  static const Color softBlue2 = Color(0xFF73A1F9);
  static const Color darkTosca = Color(0xFF00AA8E);
  static const Color softGreen = Color(0xFFA2FF86);
}
