// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-eXNRX9wvVEg6YO8W3FKKYLAjHNKbVkM',
    appId: '1:593989439104:web:7db64e2948d35aa464e065',
    messagingSenderId: '593989439104',
    projectId: 'sqlyze-7eaca',
    authDomain: 'sqlyze-7eaca.firebaseapp.com',
    storageBucket: 'sqlyze-7eaca.appspot.com',
    measurementId: 'G-5JCFCJ7N33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7_G-6N7KZVXF3HwtpjeYH6FWgC4kkQc',
    appId: '1:593989439104:android:8f5bec98ed2b32f664e065',
    messagingSenderId: '593989439104',
    projectId: 'sqlyze-7eaca',
    storageBucket: 'sqlyze-7eaca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwLzOtroQf0WzA7i1u9H3uaeBopcxyZM',
    appId: '1:593989439104:ios:61f94ea1b8cded4064e065',
    messagingSenderId: '593989439104',
    projectId: 'sqlyze-7eaca',
    storageBucket: 'sqlyze-7eaca.appspot.com',
    iosClientId:
        '593989439104-mfnmlmreaehj547ikkabv1hrlf6vr7sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sqlyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwLzOtroQf0WzA7i1u9H3uaeBopcxyZM',
    appId: '1:593989439104:ios:61f94ea1b8cded4064e065',
    messagingSenderId: '593989439104',
    projectId: 'sqlyze-7eaca',
    storageBucket: 'sqlyze-7eaca.appspot.com',
    iosClientId:
        '593989439104-mfnmlmreaehj547ikkabv1hrlf6vr7sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sqlyze',
  );
}
